changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

changesetIgnorePatterns:
  - .yarn/cache/**
  - .trunk/**
  - .husky/**
  - '**/coverage/**'
  - '**/.eslint*'
  - '**/.prettier*'
  - '**/.vscode/**'
  - '**/.markdownlint.*'
  - '**/.shellcheckrc'
  - '**/jest.config.*'

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'

yarnPath: .yarn/releases/yarn-3.3.0.cjs
