name: 🧼 Pull Request - Cleanup Tags and Releases

on:
  delete:
  pull_request:
    types: [closed]
  workflow_dispatch:
    inputs:
      regex:
        description: 'Regex to search by'
        required: false
      pr_number:
        description: 'PR Number to search by'
        required: false

permissions:
  contents: read
  pull-requests: write

jobs:
  cleanup:
    name: Cleanup Tags and Releases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: github-action-cleanup-releases-and-tags
          fetch-depth: 0
      - name: Remove unused releases and tags
        if: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} != ''
        uses: ./github-action-cleanup-releases-and-tags
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          regex: ${{ github.event.inputs.regex }}
          pr_number: ${{ github.event.inputs.pr_number }}
